language: python
python: 3.5
dist: precise
env:
  - TOX_ENV=py27
  - TOX_ENV=py33
  - TOX_ENV=py34
  - TOX_ENV=py35
  - TOX_ENV=pypy
  - TOX_ENV=flake8
  - TOX_ENV=pylint-errors
  - TOX_ENV=pylint-full
  - TOX_ENV=verify-manifest
install:
  - pip install tox
  - pip install python-coveralls
script:
  - tox -e $TOX_ENV
after_script:
  - if [ "$TOX_ENV" = "py35" ]; then tox -e coveralls; fi
notifications:
  email: false
